### ISSUE TITLE
BUG: PostgreSQL läuft angeblich nicht

### ISSUE THREAD

**Issue by ledermann** [solectrus/backup-restore#1]
> ich bekomme es leider nicht zum laufen. Folgender Fehler erscheint. Solectrus läuft aber und ist nicht beendet.

```
pi@raspberrypi:~/solectrus $ ./backup.sh
Checking if PostgreSQL and InfluxDB containers are running...
Error: PostgreSQL container is not running.
```

_Originally posted by @StevieC121176 in https://github.com/solectrus/solectrus/discussions/2860#discussioncomment-10857813_

**Comment by ledermann** [comment]
@StevieC121176 Was ergibt bei dir das hier?

```
docker compose ps --services --filter "status=running"
```

Meine Vermutung: Dein PostgreSQL-Service heißt anders. In den Anfangstagen von SOLECTRUS hatte ich den in der Installations-Anleitung `db` genannt, vermutlich ist das bei dir noch so. Kannst du das bestätigen? Ich passe das Script dann an, dass es beides erkennt.

**Comment by ledermann** [comment]
Habe es gerade so abgeändert, dass der PostgreSQL-Service sowohl `db` als auch `postgresql` heißen darf. Nach einem erneuten `curl` sollte es jetzt auch bei dir klappen.

**Comment by StevieC121176** [comment]
ja du hast recht, bei mir heißt der noch `db`

```
pi@raspberrypi:~/solectrus $ docker compose ps --services --filter "status=running"
app
db
forecast-collector
influxdb
mqtt-collector
power-splitter
redis
shelly-collector
watchtower
```

**Comment by StevieC121176** [comment]
@ledermann  nach erneutem `curl `funktioniert das Backup jetzt

**Comment by ledermann** [comment]
Prima!
