### ISSUE TITLE
auf Synology wird "docker compose" nicht erkannt

### ISSUE THREAD

**Issue by halmich** [solectrus/backup-restore#2]
Erst mal vielen Dank für das Skript!
Für diejenigen, die ein Synology-Nas nutzen noch der Hinweis, dass im Skript der Befehl "docker-compose" (anstatt "docker cmpose") benutzt werden muss.

**Comment by ledermann** [comment]
Guter Hinweis, danke. Das werde ich noch anpassen, sodass automatisch erkannt wird, welche Variante genommen werden muss.

**Comment by ledermann** [comment]
Habe das gerade ergänzt. Die beiden Scripte erkennen jetzt automatisch, ob es `docker compose` oder `docker-compose` heißen muss. Man muss also nichts weiter beachten.

Vielleicht magst du es ausprobieren. Einfach nochmal die beiden `curl`-Statements ausführen, um die aktualisierte Fassung herunterzuladen.

**Comment by halmich** [comment]
Ja, get_docker_compose_command läuft und es klappt nun ohne eigene Anpassung.
Perfekt! :)
Diese Warnungen sind nicht ungewöhnlich, oder?
![grafik](https://github.com/user-attachments/assets/32dbcce1-d310-4134-8dea-0b5954b09a88)

**Comment by ledermann** [comment]
Die Warnungen "Shard XXX removed during backup" klingen tatsächlich seltsam, ich sehe das bei mir übrigens **nicht**.

Andere InfluxDB-User berichten aber ebenfalls von diesen Warnungen, Probleme scheint es nicht zu bereiten. Es gibt die Vermutung, dass es sich um leere Shards handelt:
https://github.com/influxdata/influxdb/issues/23854

Ein Shard deckt in InfluxDB eine bestimmte Zeitspanne ab, bei mir scheint es eine Woche zu sein (kann man dem Manifest entnehmen, das in der `.tar`-Datei steckt).

**Comment by halmich** [comment]
Bei mir deckt ein shard ebenfalls eine Woche ab. 
Die ersten 164 Shards laufen schön durch von 1 bis 164.
Danach springt es auf 172, dann 180, 188, 196, 204, 212, 220, 228, 236, 244, 252
164 war die Woche vom **22.7-29.7.24**,   172 ist dann vom 29.07.-05.8.

In dieser Woche hatten wir E-Mail Kontakt. Da ging es darum, dass der Wallboxverbrauch aus Solectrus nicht mit dem der Wallbox selbst übereinstimmt. Ich habe dann beim MQTT die Einstellungen angepasst ("publish nur bei Änderungen",...), du hast jedoch ebenfalls den MQTT Collector angepasst.

> Dank deines Log-Auszugs ist mir der Fehler klar geworden: Der MQTT-Collector konvertiert (entgegen meiner Erwartung) im Fall von JSON einen NULL-Wert nicht zu 0. Der Verbrauch deiner Wärmepumpe wird korrekt geschrieben, aber der Wert der Wallbox nur dann, wenn er nicht NULL ist.

Das war am **26.07**. Hier bin ich zur Entwicklerversion gewechselt. Ob das ursächlich ist weiß ich nicht.
Ansonsten habe ich soweit ich weiß an meiner Solectrus Instanz nichts verändert.

Es fehlen nun immer "7 Shards". Diese 7 tauchen oben in den Warnungen auf (260 ist dann wieder drin).

Ich sehe es wie du, es sind leere Shards die gelöscht wurden und daher ist das Backup recht wahrscheinlich vollständig und funktioniert. Warum jedoch seit Ende Juli immer 7 leere Shards erzeugt werden kann ich nicht erklären. Da verstehe ich die Materie zu wenig.

Edit:
Kam nicht Ende Juli auch noch der PowerSplitter?

Edit:
Der kam am 07.08., hmm, dann kanns daran wohl nicht liegen, da die ersten Shards schon am 30.07. "gelöscht" wurden.

**Comment by ledermann** [comment]
Da kann ich leider auch wenig zur Klärung beitragen. Wie InfluxDB die Shards intern organisiert, ist mir auch nicht im Detail bekannt. Hier wird das ein wenig beschrieben:
https://docs.influxdata.com/influxdb/v2/reference/internals/shards

Ob und wie die verschiedenen Änderungen in SOLECTRUS und seinen Komponenten Einfluss auf die Shards in InfluxDB haben, kann ich nicht beurteilen. 

In den vier Jahren, in denen ich hier intensiv mit InfluxDB zu tun habe, gab es nie das kleinste Problem damit. Und ich mache hier so einiges an Experimenten damit. Insgesamt denke ich, dass man sich wegen der Warnungen eher keine Sorgen machen muss. Die Warnung ist vermutlich nur ungünstig formuliert.

Um ganz sicherzugehen, kannst du natürlich mal ein Restore probieren und gucken, ob sich alles wiederfindet. Grundsätzlich gehört es ja zu jeder Backup-Strategie, dass man die Backups auch mal testet (auf einem separaten System natürlich). Ob man sich den Aufwand antun möchte, ist natürlich eine andere Frage. Das mache ich auch zu selten ;-)

These: Wenn du ein Restore durchführst und anschließend wieder ein Backup, wird es keine Warnung mehr geben, da die leeren Shards dadurch verschwinden (weil sie nicht Teil des Backups sind und somit nicht wiederhergestellt werden).

**Comment by halmich** [comment]
> These: Wenn du ein Restore durchführst und anschließend wieder ein Backup, wird es keine Warnung mehr geben, da die leeren Shards dadurch verschwinden (weil sie nicht Teil des Backups sind und somit nicht wiederhergestellt werden).

Die leeren Shards sind im Backup gar nicht vorhanden. Ich tippe auch darauf, dass beim Backup in ein paar Wochen die Zahlen 253-259 gar nicht mehr auftauchen werden, sondern dann eben Zahlen im Bereich von 280-290...
Ich bin mir recht sicher, dass das Backup funktionieren würde (aber ja, ich teste es mal auf meinem Raspi!), mich wundert es nur grundsätzlich, dass Zahlen übersprungen werden.

Danke!
Kannst das issue hier jedenfalls schließen :)
