### ISSUE TITLE
Restore der PostgreSQL-Datenbank funktioniert nicht

### ISSUE THREAD

**Issue by gereons** [solectrus/backup-restore#3]
Ich habe eben (testhalber, in einer neuen & leeren Solectrus-Instanz) versucht einen meiner Solectrus-Backups wieder zu restoren, was laut Script-Ausgabe auch erfolgreich war. Leider fehlen aber danach sämtliche Daten in PostgreSQL.

Was ich in den Einstellungen sehe ist ein Strompreis von 0,2545 € und eine Einspeisevergütung von 0,0832 € was die Defaultwerte aus dem Code sind, wenn ich das richtig sehe.

Ich habe daraufhin mal das restore-Script so geändert dass der Output des psql-Kommandos nicht verworfen wird, und bekomme dann das hier:

```
SET
SET
SET
ERROR:  role "postgres" already exists
ALTER ROLE
You are now connected to database "template1" as user "postgres".
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
You are now connected to database "postgres" as user "postgres".
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
ERROR:  database "solectrus_production" already exists
ALTER DATABASE
You are now connected to database "solectrus_production" as user "postgres".
SET
SET
SET
SET
SET
 set_config 
------------
 
(1 row)

SET
SET
SET
SET
SET
SET
ERROR:  relation "ar_internal_metadata" already exists
ALTER TABLE
ERROR:  relation "prices" already exists
ALTER TABLE
ERROR:  relation "prices_id_seq" already exists
ALTER SEQUENCE
ALTER SEQUENCE
ERROR:  relation "schema_migrations" already exists
ALTER TABLE
ERROR:  relation "settings" already exists
ALTER TABLE
ERROR:  relation "settings_id_seq" already exists
ALTER SEQUENCE
ALTER SEQUENCE
ALTER TABLE
ALTER TABLE
ERROR:  duplicate key value violates unique constraint "ar_internal_metadata_pkey"
DETAIL:  Key (key)=(environment) already exists.
CONTEXT:  COPY ar_internal_metadata, line 1
ERROR:  duplicate key value violates unique constraint "prices_pkey"
DETAIL:  Key (id)=(2) already exists.
CONTEXT:  COPY prices, line 1
ERROR:  duplicate key value violates unique constraint "schema_migrations_pkey"
DETAIL:  Key (version)=(20230809043814) already exists.
CONTEXT:  COPY schema_migrations, line 1
ERROR:  duplicate key value violates unique constraint "settings_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY settings, line 1
 setval 
--------
      6
(1 row)

 setval 
--------
      5
(1 row)

ERROR:  multiple primary keys for table "ar_internal_metadata" are not allowed
ERROR:  multiple primary keys for table "prices" are not allowed
ERROR:  multiple primary keys for table "schema_migrations" are not allowed
ERROR:  multiple primary keys for table "settings" are not allowed
ERROR:  relation "index_prices_on_name_and_starts_at" already exists
ERROR:  relation "index_settings_on_var" already exists
```

Das klingt für mich so als ob da vor dem Einspielen des Backups noch ein "Lösche alle Tabellen, Indizes und Sequences" fehlt.

**Comment by ledermann** [comment]
@gereons Danke für den Hinweis, du hast vollkommen recht. Das Backup wird zwar korrekt erstellt, das Wiederherstellen scheitert aber an vorhandenen Daten - und man sieht den Fehler gar nicht.

Ich habe zwei Dinge geändert:

1) Fehlermeldungen werden nicht mehr unterdrückt
2) Ein Backup wird jetzt mit DROP-Statements erzeugt, sodass beim Restore automatisch die vorhandenen Objekte gelöscht werden.

Ein explizites Löschen vor dem Restore wäre theoretisch zwar auch möglich, ist aber etwas fummelig. Somit nehme ich in Kauf, dass alte Backups weiterhin beim Restore fehlschlagen, wobei man das nun aber besser sieht.

**Comment by gereons** [comment]
Gerade mit den neuen Versionen der Scripte getestet - funktioniert jetzt wie erwartet, danke!

Vermutlich ist es sinnvoll nochmal prominent darauf hinzuweisen dass diejenigen, die diese Scripte schon runtergeladen haben das jetzt nochmal tun.
