### ISSUE TITLE
Automatisierte Sicherung

### ISSUE THREAD

**Issue by 17032001** [solectrus/backup-restore#4]
Guten Tag,

wäre es möglich das Backup.sh Skript so anzupassen das ich es auch außerhalb des Verzeichnisses ausführen kann. Und in der Corntab hinterlegen.

Vielen Dank fürs Feedback.

**Comment by ledermann** [comment]
Das müsste ohne Änderung des Skriptes so gehen:

`crontab -e`, dann das eintragen:

```
0 2 * * * cd /home/[username]/solectrus && ./backup.sh
```

(Name des Ordners anpassen)

**Comment by 17032001** [comment]
Herzlichen Dank funktioniertMit freundlichen GrüßenVon meinem iPhone gesendetAm 27.11.2024 um 14:57 schrieb Georg Ledermann ***@***.***>:﻿
Das müsste ohne Änderung des Skriptes so gehen:
crontab -e, dann das eintragen:
0 2 * * * cd /home/[username]/solectrus && ./backup.sh

(Name des Ordners anpassen)
